### ISSUE TITLE
Update to support Raven > 2.0.0

### ISSUE THREAD

**Issue by grimurd** [guzru/winston-sentry#28]
This package isn't working properly for me with Sentry version 8.2.  (each error is reported to sentry but they are reported as a regression of a previous error even though they arent related.)

The raven dependency should be updated to version ^2.0.0

**Comment by ateev** [comment]
@guzru Same for me. Can you update the underscore version too ?

**Comment by Sk1Zy** [comment]
Think @shaharke is maintaining this now.

**Comment by dhritzkiv** [comment]
I think winston-sentry uses `raven` (https://github.com/getsentry/raven-node) which is at v0.11. `raven-js`, the browser version has version v2 (the latest is now v3).

So the `raven` dep should still be updated, just the version its updating to is v0.11
