### ISSUE TITLE
Log Level seems to be ignored

### ISSUE THREAD

**Issue by felixheck** [guzru/winston-sentry#31]
Hey guys,

I'm currently using `winston-sentry` in an `express` application, like below:

```
var logger = new winston.Logger({
    transports: [
        new WinstonSentry({
            level: 'error',
            dsn: '{{ MY_DSN }}'
        })
    ],
    exceptionHandlers: [
        new winston.transports.File({
            filename: '{{ MY_FILENAME }}',
            json: false
        })
    ],
    exitOnError: false
});
```

Whenever I call `logger.info()` the passed message will be send to Sentry despite the mismatch concerning the log level.

Have you got any hints?
Thanks!

**Comment by mathieumg** [comment]
I have the same problem since 0.1.2 as well!

**Comment by shaharke** [comment]
@felixheck @mathieumg problem was fixed. Upgrade to 0.1.3

**Comment by felixheck** [comment]
Yeah, that was fast. Love it. Thanks man!
